# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'rwotest'
    runOptions: 'inline'
    inline: |
      ls
      cd Python
      git fetch
      git status
      git pull
      python3 rwo.py
      ./rwo_bash.sh
      echo bro
    readyTimeout: '20000'